### ISSUE TITLE
Option to report glyph run with unscaled values

### ISSUE THREAD

**Issue by simoncozens** [miloush/dwbox#10]
When debugging a font it's easier if often everything is done at upem scale, so that the debugging process is not distracted with floating point, rounding, small values, etc. Also makes it easier to compare with other shaping engines.

**Comment by miloush** [comment]
DWrite reports scaled values only, but I gave you an option to show the reverse-calculated values, I checked a few glyphs and it seems to be reporting the correct values.

Just right-click on the table:

![image](https://github.com/user-attachments/assets/1f23c507-14a6-4203-926e-603e7013e04c)
