### ISSUE TITLE
Allow any BCP-47 tag

### ISSUE THREAD

**Issue by devosb** [miloush/dwbox#18]
With DWBox 2.4.0.0 from the release page on Windows 11 (build 22000.160 from running Windows Insiders but not updated in a while, but still more than the minimum stated build of 20348) I can select different BCP-47 tags from a good sized drop down list and see the text shaping change. I can also type a BCP-47 tag, and if that tag is on the list, then the text shaping also happens.

As far as I can tell, I cannot type any BCP-47 and have it affect the text shaping. Since I need to test with BCP-47 tags not on the list (for some lesser known languages) is there a way to do this with DWBox? If not, can such functionality be added?

**Comment by miloush** [comment]
Any text typed in the combo box should be passed to DWrite. Do you have a repro font and tag which don't work?

**Comment by devosb** [comment]
Yes, [Padauk 5.001](https://software.sil.org/padauk/download/), with tag `ksw` (for S’gaw Karen). With this tag specified, the dot should be on the left, as you can see in the screenshot from Firefox below. The _label_ column gives the codepoints, and the _Padauk_ column shows the expected shaping. The 2nd and 4th lines in the table (with ksw in both the _label_ and the _style_ columns) shows that the language setting works.
![image](https://github.com/user-attachments/assets/af678d4c-342f-4559-8c99-bd57cf2dac89)

**Comment by devosb** [comment]
[Scheherazade New 4.300](https://software.sil.org/scheherazade/download/) as well shows the issue. The codepoints I used are `0628 0651 0650`, you can see the [expected shaping](https://software.sil.org/scheherazade/features/) in the _0650/064E_ column. Red text indicates that the specified language is causing that bit of text to change. The tag `rhg` does not cause the expected shaping change with DWBox.

**Comment by miloush** [comment]
Right, thank you. As I said DWBox passes any text for the language directly to DirectWrite. There is no DW API which would allow to supply OpenType tags directly, and the OT language tags specifically contain a space, so they are not valid BCP-47 subtags. DW therefore has to somehow come up with the OT script and language tag from the supplied BCP-47 tag. I am afraid it doesn't have the mapping for languages like Rohingya and S'gaw Karen yet, and I don't see a way how API callers can work around it.

**Comment by devosb** [comment]
Thanks for the helpful explanation, I appreciate it. Maybe I need a newer version of DirectWrite, as `ksw` and `rhg` are listed by Microsoft in their [mapping of ISO 639-3 codes to OT language tags](https://learn.microsoft.com/en-us/typography/opentype/spec/languagetags).

**Comment by miloush** [comment]
I tried on the newest DirectWrite but these are not in yet. I forwarded the feedback and hope the OT mapping will be utilized.

**Comment by devosb** [comment]
Thanks for the additional testing and reporting the issue. Both very appreciated.
