### ISSUE TITLE
Can UAM.Interop.DirectWrite replace the DirectWriteForwarder of wpf?

### ISSUE THREAD

**Issue by lindexi** [miloush/dwbox#6]
I find the UAM.Interop.DirectWrite can use `DWriteFactory.Shared7.GetSystemFontSet2` to get the font set. And the `DWriteFactory.Shared7.CreateTextFormat` can create the text format. And the `DWriteFactory.Shared7.CreateTextLayout` can create the text layout.

Oh, good. This is the core function of DirectWriteForwarder ! You did very well!

**Comment by miloush** [comment]
Thanks!

I have handwritten all these interfaces using `[ComImport]`. I believe the direction over in WPF is to depart from using `[ComImport]` and use the trimmable declarations with pointers.
